encoder:
  type: 'resnet34'
model:
  type: 'multilosses'
  Y_losses: []
  Z_losses:
  - name: 'infonce'
    weight: 1.0
data:
  siamese: true
  train: 'voxceleb1_train.csv'
  augmentation:
    enable: true