encoder:
  type: 'resnet34'
model:
  type: 'supervised'
  nb_classes: 5994
training:
  epochs: 200
evaluation:
  mean_of_features: false
  num_frames: 10
  frame_length: 64000
data:
  train: 'voxceleb2_train.csv'
  augmentation:
    enable: true