encoder:
  type: 'resnet34'
method:
  type: 'simclr_margins'
  scale: 30
  enable_projector: false
  loss: 'nt-xent-curricularface'
  margin: 0.1
  ssps:
    start_epoch: 100
    verbose: true
    sampling: 'kmeans-repr'
    kmeans_nb_prototypes: 25000
    inter_sampling_size: 1
    pos_queue_size: 25000
trainer:
  last_checkpoint: 'models/ssps/voxceleb2/simclr_p-none/_simclr/checkpoints/model_latest_ssps-25k.pt'
  epochs: 110
evaluation:
  validation:
    - type: 'sv_cosine'
  test:
    - type: 'sv_cosine'
      frame_length: null
dataset:
  ssl: true
  ssps: true
  train: 'voxceleb2_train.csv'
  augmentation:
    enable: true
