wandb_project: 'sslsv_theo_experiments'
encoder:
  type: 'resnet34'
model:
  type: 'custom'
  enable_projector: false
  loss_name: 'nt-xent'
training:
  epochs: 1
data:
  max_samples: 100000
  siamese: true
  train: 'voxceleb2_train'
  augmentation:
    enable: true
