wandb_project: 'sslsv_theo_experiments'
encoder:
  type: 'resnet34'
model:
  type: 'moco'
training:
  epochs: 150
  batch_size: 200
  ddp_sync_batchnorm: false
evaluation:
  mean_of_features: false
  num_frames: 10
  frame_length: 56240
data:
  siamese: true
  train: 'voxceleb2_train.csv'
  augmentation:
    enable: true