wandb_project: 'sslsv_theo_experiments'
encoder:
  type: 'resnet34'
  mel_n_mels: 80
model:
  type: 'custom'
training:
  epochs: 200
data:
  siamese: true
  train: 'voxceleb1_train'
  wav_augment:
    enable: true
