seed: 1718
wandb_project: 'sslsv_theo_experiments'
encoder:
  type: 'resnet34'
model:
  type: 'custom'
training:
  epochs: 202
data:
  siamese: true
  train: 'voxceleb1_train'
  wav_augment:
    enable: true
