wandb_project: 'sslsv_theo_experiments'
encoder:
  type: 'resnet34'
model:
  type: 'custom'
training:
  epochs: 200
data:
  frame_length: 48000
  siamese: true
  train: 'voxceleb1_train'
  wav_augment:
    enable: true
