wandb_project: 'sslsv_theo_experiments'
encoder:
  type: 'ecapatdnn'
  encoder_dim: 1024
model:
  type: 'custom'
training:
  epochs: 200
data:
  siamese: true
  train: 'voxceleb1_train'
  wav_augment:
    enable: true
