wandb_project: 'sslsv_theo_experiments'
encoder:
  type: 'resnet34'
model:
  type: 'custom'
  enable_projector: false
  loss_name: 'snt-xent-am'
  loss_scale: 30
  loss_margin: 0.1
training:
  epochs: 150
  batch_size: 200
evaluation:
  mean_of_features: false
  num_frames: 10
  frame_length: 56240
data:
  siamese: true
  train: 'voxceleb1_train.csv'
  augmentation:
    enable: true