encoder:
  type: 'resnet34'
method:
  type: 'simclr_margins'
  scale: 30
  enable_projector: false
  loss: 'nt-xent-adaface'
  margin: 0.2
  ssps:
    start_epoch: 100
    verbose: true
    sampling: 'kmeans-repr'
    kmeans_nb_prototypes: 25000
    inter_sampling_size: 1
trainer:
  last_checkpoint: 'models/ssps/voxceleb2/simclr/_simclr/checkpoints/model_latest.pt'
  batch_size: 200
  epochs: 110
evaluation:
  validation:
    - type: 'sv_cosine'
  test:
    - type: 'sv_cosine'
      frame_length: null
dataset:
  ssl: true
  ssps: true
  train: 'voxceleb2_train.csv'
  augmentation:
    enable: true
