wandb_project: 'sslsv_interspeech_2023'
encoder:
  type: 'resnet34'
  base_dim: 16
  encoder_dim: 512
model:
  type: 'custom'
  loss_name: 'aamsoftmax'
  loss_margin: 0.01
training:
  epochs: 200
data:
  siamese: true
  train: 'voxceleb1_train'
  wav_augment:
    enable: true