wandb_project: 'sslsv_interspeech_2023'
encoder:
  type: 'resnet34'
  base_dim: 16
  encoder_dim: 512
model:
  type: 'custom'
  loss_name: 'aamsoftmax'
  loss_margin: 0.01
  loss_reg_weight: 0.1
training:
  epochs: 200
data:
  siamese: true
  train: './data/voxceleb1_train_list'
  wav_augment:
    enable: true