wandb_project: 'sslsv_interspeech_2023'
encoder:
  type: 'resnet34'
model:
  type: 'custom'
  loss_name: 'snt-xent-am'
  loss_margin: 0.0
  loss_margin_learnable: true
training:
  epochs: 200
data:
  siamese: true
  train: 'voxceleb1_train'
  wav_augment:
    enable: true