wandb_project: 'sslsv_interspeech_2023'
encoder:
  type: 'resnet34'
model:
  type: 'custom'
  loss_name: 'snt-xent-aam'
  loss_margin: 0.3
training:
  epochs: 200
data:
  siamese: true
  train: 'voxceleb1_train.csv'
  augmentation:
    enable: true