wandb_project: 'sslsv_interspeech_2023'
encoder:
  type: 'resnet34'
  encoder_dim: 1024
  base_dim: 32
model:
  type: 'custom'
  loss_name: 'snt-xent'
training:
  epochs: 300
data:
  siamese: true
  train: 'voxceleb1_train'
  augmentation:
    enable: true