wandb_project: 'sslsv_interspeech_2023'
encoder:
  type: 'resnet34'
model:
  type: 'custom'
  loss_name: 'snt-xent'
  enable_projector: false
training:
  epochs: 200
data:
  siamese: true
  train: 'voxceleb1_train'
  augmentation:
    enable: true