wandb_id: '__DEBUG__1'
model:
  type: 'simclr'
  infonce_weight: 0.0
  vicreg_weight: 1.0
  barlowtwins_weight: 0.0
training:
  batch_size: 4
data:
  train: './data/voxceleb1_train_list'
  max_samples: 12
  wav_augment:
    enable: true