wandb_id: '__DEBUG__1'
encoder:
  type: 'resnet34'
model:
  type: 'simclr'
training:
  batch_size: 4
data:
  siamese: true
  train: './data/voxceleb1_train_list'
  max_samples: 12
  wav_augment:
    enable: false