wandb_id: '__DEBUG__1'
encoder:
  type: 'resnet34'
model:
  type: 'custom'
  loss_name: 'nt-xent'
  loss_reg_weight: 0.0
  enable_projector: true
  enable_multi_views: false
  loss_margin_learnable: false
training:
  batch_size: 4
evaluate:
  batch_size: 16
data:
  siamese: true
  train: 'voxceleb1_train'
  val: 'voxceleb1_test_O_DEBUG'
  max_samples: 12
  augmentation:
    enable: false