wandb_id: '__DEBUG__1'
encoder:
  type: 'resnet34'
model:
  type: 'custom'
  loss_name: 'aamsoftmax'
  loss_reg_weight: 0.1
  enable_projector: false
  enable_multi_views: true
  loss_margin_learnable: true
training:
  batch_size: 4
evaluate:
  batch_size: 16
data:
  siamese: true
  train: 'voxceleb1_train'
  val: 'voxceleb1_test_O_DEBUG'
  max_samples: 12
  wav_augment:
    enable: false