encoder:
  type: 'thinresnet34'
model:
  type: 'simsiam'
training:
  optimizer: 'sgd'
  weight_decay: 0.0001
  learning_rate: 0.05
data:
  train: './data/voxceleb1_train_list'
  wav_augment:
    enable: true