encoder:
  type: 'resnet34'
  base_dim: 8
  encoder_dim: 256
model:
  type: 'supervised'
  nb_classes: 2
  speaker_classification: false
training:
  epochs: 200
  tracked_metric: 'val/classification/voxceleb1_train_gender/accuracy'
  tracked_mode: 'max'
evaluation:
  mean_of_features: false
  num_frames: 1
  frame_length: 64000
  validation:
    - type: 'classification'
      csv: 'voxceleb1_train_gender.csv'
      key: 'Gender'
  test:
    - type: 'classification'
      csv: 'voxceleb1_train_gender.csv'
      key: 'Gender'
data:
  train: 'voxceleb1_train_gender.csv'
  label_key: 'Gender'
  augmentation:
    enable: true