encoder:
  type: 'resnet34'
  pooling_mode: 'stats'
  mel_n_mels: 80
method:
  type: 'dino'
  global_count: 1
  local_count: 4
trainer:
  epochs: 80
  batch_size: 128
  optimizer: 'sgd'
  learning_rate: 0.2
  weight_decay: 0.00005
evaluation:
  validation:
    - type: 'sv_cosine'
  test:
    - type: 'sv_cosine'
      frame_length: null
dataset:
  ssl: true
  ssl_dino_global_count: 1
  ssl_dino_global_length: 32000
  ssl_dino_local_count: 4
  ssl_dino_local_length: 32000
  frame_sampling: 'dino'
  train: 'voxceleb2_train.csv'
  augmentation:
    enable: true
    strategy: 'all'
